### PR TITLE
Make all optional fields

### PR DESCRIPTION
**Pull request by ahuang11**
## Summary

"When instance_pool_id is already specified in prefect.tasks.databricks.models.NewCluster model, node_type_id should not be required."

With this PR, users will have to read the docs to search for required inputs, e.g.:
```
    node_type_id: Optional[str] = Field(
        None,
        description=(
            "This field encodes, through a single value, the resources available to"
            " each of the Spark nodes in this cluster. For example, the Spark nodes can"
            " be provisioned and optimized for memory or compute intensive workloads A"
            " list of available node types can be retrieved by using the [List node"
            " types](https://docs.databricks.com/dev-tools/api/latest/clusters.html#list-node-types)"
            " API call. This field is required."
        ),
    )
```

Or run it and get back a descriptive error:
```
HTTPStatusError: The request was malformed. See JSON response for error details.JSON response: {'error_code': 'INVALID_PARAMETER_VALUE', 'message': "Missing required field 'node_type_id'"}
```

## Relevant Issue(s)

Closes https://github.com/PrefectHQ/prefect/issues/5890

## Checklist
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-databricks/blob/main/CHANGELOG.md)

### CODE REVIEW

**Review by desertaxle — COMMENTED** [review]
I think this might be a bit of an over correction. Couldn't we update the fields mentioned in the issue to be optional in the OpenAPI spec?

**Comment by ahuang11** [comment]
> Couldn't we update the fields mentioned in the issue to be optional in the OpenAPI spec?

I think it'd be overwritten every time on new generation.

**Comment by desertaxle** [comment]
> I think it'd be overwritten every time on new generation.

Why would it be overwritten on each generation?

**Comment by ahuang11** [comment]
Well depends on whether the paths_or_urls kwarg is pointed to a local file or a remote url. For prefect-databricks, it's pointed to a URL; that way, it overwrites the latest spec each time.
https://github.com/PrefectHQ/prefect-databricks/blob/main/scripts/generate.py#L35

However, I guess there's a way around it by using the preprocess_fn capability
https://github.com/PrefectHQ/prefect-databricks/blob/main/scripts/generate.py#L40

**Comment by ahuang11** [comment]
Reopening this so I can implement the aforementioned fix.

**Comment by ahuang11** [comment]
https://github.com/PrefectHQ/prefect-databricks/pull/25/files fixes the issue in a targeted way

**Pull request closed without merging**
